"""
Manual recipe seeder — no LLM API calls.

Defines 120 recipes (30 per meal type) with estimated calories + protein.
Derives carbs/fat via src.nutrition.calculations.calculate_macros().
Inserts directly into Supabase recipes table.

Run: python scripts/seed_recipes_manual.py
"""

import asyncio
import unicodedata
import logging
from dotenv import load_dotenv
from pathlib import Path

load_dotenv(Path(__file__).resolve().parent.parent / ".env", override=True)

from src.clients import get_supabase_client
from src.nutrition.calculations import calculate_macros
from src.nutrition.openfoodfacts_client import off_validate_recipe

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)


def normalize(name: str) -> str:
    """Lowercase + strip accents for deduplication."""
    nfkd = unicodedata.normalize("NFKD", name.lower())
    return "".join(c for c in nfkd if not unicodedata.combining(c))


# ---------------------------------------------------------------------------
# Recipe definitions: only fill what we know — macros computed automatically
# Format: (name, calories, protein_g, meal_type, cuisine, diet, prep_min,
#          ingredients, instructions, tags, allergen_tags)
# ---------------------------------------------------------------------------

RECIPES = [
    # ── PETIT-DÉJEUNER ──────────────────────────────────────────────────────
    (
        "Omelette aux herbes et fromage",
        380,
        28,
        "petit-dejeuner",
        "française",
        "omnivore",
        10,
        [
            {"name": "Œufs", "quantity": 3, "unit": "pièces"},
            {"name": "Gruyère râpé", "quantity": 30, "unit": "g"},
            {"name": "Ciboulette", "quantity": 10, "unit": "g"},
            {"name": "Beurre", "quantity": 10, "unit": "g"},
        ],
        "Battre les œufs, ajouter le fromage et la ciboulette. Cuire dans le beurre à feu moyen 3 min.",
        ["high-protein", "low-carb", "quick"],
        ["gluten", "lactose", "oeuf"],
    ),
    (
        "Bol d'avoine aux fruits rouges",
        420,
        14,
        "petit-dejeuner",
        "internationale",
        "végétarien",
        5,
        [
            {"name": "Flocons d'avoine", "quantity": 80, "unit": "g"},
            {"name": "Lait demi-écrémé", "quantity": 200, "unit": "ml"},
            {"name": "Fruits rouges mélangés", "quantity": 100, "unit": "g"},
            {"name": "Miel", "quantity": 15, "unit": "g"},
        ],
        "Chauffer le lait, verser sur les flocons. Laisser gonfler 3 min. Ajouter fruits et miel.",
        ["high-carb", "vegetarian", "quick"],
        ["gluten", "lactose"],
    ),
    (
        "Toast avocat et œuf poché",
        380,
        16,
        "petit-dejeuner",
        "internationale",
        "végétarien",
        10,
        [
            {"name": "Pain complet", "quantity": 2, "unit": "tranches"},
            {"name": "Avocat", "quantity": 80, "unit": "g"},
            {"name": "Œuf", "quantity": 1, "unit": "pièce"},
            {"name": "Jus de citron", "quantity": 5, "unit": "ml"},
        ],
        "Toaster le pain. Écraser l'avocat avec le citron. Pocher l'œuf 3 min. Assembler.",
        ["vegetarian", "healthy-fats", "quick"],
        ["gluten", "oeuf"],
    ),
    (
        "Yaourt grec granola et miel",
        360,
        18,
        "petit-dejeuner",
        "méditerranéenne",
        "végétarien",
        5,
        [
            {"name": "Yaourt grec", "quantity": 200, "unit": "g"},
            {"name": "Granola", "quantity": 50, "unit": "g"},
            {"name": "Miel", "quantity": 15, "unit": "g"},
            {"name": "Noix", "quantity": 20, "unit": "g"},
        ],
        "Verser le yaourt dans un bol. Ajouter le granola, les noix et le miel.",
        ["high-protein", "vegetarian", "quick"],
        ["lactose", "gluten", "noix"],
    ),
    (
        "Galette sarrasin jambon fromage",
        420,
        24,
        "petit-dejeuner",
        "française",
        "omnivore",
        15,
        [
            {"name": "Farine de sarrasin", "quantity": 60, "unit": "g"},
            {"name": "Jambon blanc", "quantity": 60, "unit": "g"},
            {"name": "Emmental râpé", "quantity": 30, "unit": "g"},
            {"name": "Œuf", "quantity": 1, "unit": "pièce"},
        ],
        "Préparer la pâte sarrasin avec eau. Cuire la galette, garnir jambon, fromage et œuf.",
        ["high-protein", "gluten-free-option", "traditional"],
        ["lactose", "oeuf"],
    ),
    (
        "Smoothie protéiné banane épinards",
        340,
        22,
        "petit-dejeuner",
        "internationale",
        "végétarien",
        5,
        [
            {"name": "Banane", "quantity": 1, "unit": "pièce"},
            {"name": "Épinards frais", "quantity": 50, "unit": "g"},
            {"name": "Lait demi-écrémé", "quantity": 200, "unit": "ml"},
            {"name": "Protéine en poudre vanille", "quantity": 30, "unit": "g"},
        ],
        "Mixer tous les ingrédients jusqu'à consistance lisse. Servir frais.",
        ["high-protein", "vegetarian", "quick", "smoothie"],
        ["lactose"],
    ),
    (
        "Pain complet beurre d'amande et banane",
        400,
        12,
        "petit-dejeuner",
        "internationale",
        "végétarien",
        5,
        [
            {"name": "Pain complet", "quantity": 2, "unit": "tranches"},
            {"name": "Beurre d'amande", "quantity": 30, "unit": "g"},
            {"name": "Banane", "quantity": 1, "unit": "pièce"},
        ],
        "Toaster le pain. Tartiner de beurre d'amande. Trancher la banane dessus.",
        ["vegetarian", "quick", "energy"],
        ["gluten", "noix"],
    ),
    (
        "Fromage blanc fruits et graines",
        300,
        20,
        "petit-dejeuner",
        "française",
        "végétarien",
        5,
        [
            {"name": "Fromage blanc 0%", "quantity": 200, "unit": "g"},
            {"name": "Fruits rouges", "quantity": 80, "unit": "g"},
            {"name": "Graines de chia", "quantity": 15, "unit": "g"},
            {"name": "Miel", "quantity": 10, "unit": "g"},
        ],
        "Mélanger le fromage blanc et le miel. Ajouter les fruits et les graines.",
        ["high-protein", "vegetarian", "low-cal", "quick"],
        ["lactose"],
    ),
    (
        "Crêpe protéinée avoine banane",
        360,
        20,
        "petit-dejeuner",
        "française",
        "végétarien",
        15,
        [
            {"name": "Flocons d'avoine mixés", "quantity": 60, "unit": "g"},
            {"name": "Œuf", "quantity": 2, "unit": "pièces"},
            {"name": "Banane", "quantity": 1, "unit": "pièce"},
            {"name": "Lait", "quantity": 50, "unit": "ml"},
        ],
        "Mixer avoine, œufs, banane et lait. Cuire comme des crêpes épaisses à feu moyen.",
        ["high-protein", "vegetarian", "gluten-free-option"],
        ["gluten", "oeuf", "lactose"],
    ),
    (
        "Pain perdu cannelle et lait",
        420,
        16,
        "petit-dejeuner",
        "française",
        "omnivore",
        15,
        [
            {"name": "Pain de mie", "quantity": 2, "unit": "tranches"},
            {"name": "Œuf", "quantity": 2, "unit": "pièces"},
            {"name": "Lait", "quantity": 100, "unit": "ml"},
            {"name": "Cannelle", "quantity": 2, "unit": "g"},
            {"name": "Beurre", "quantity": 10, "unit": "g"},
        ],
        "Battre œufs, lait et cannelle. Tremper le pain. Dorer au beurre 2 min par face.",
        ["traditional", "vegetarian", "comfort"],
        ["gluten", "oeuf", "lactose"],
    ),
    # ── PETIT-DÉJEUNER (batch 2) ─────────────────────────────────────────────
    (
        "Porridge protéiné whey banane",
        480,
        30,
        "petit-dejeuner",
        "internationale",
        "végétarien",
        5,
        [
            {"name": "Flocons d'avoine", "quantity": 80, "unit": "g"},
            {"name": "Protéine en poudre vanille", "quantity": 30, "unit": "g"},
            {"name": "Banane", "quantity": 1, "unit": "pièce"},
            {"name": "Lait demi-écrémé", "quantity": 200, "unit": "ml"},
        ],
        "Cuire les flocons dans le lait. Incorporer la whey hors du feu. Ajouter la banane tranchée.",
        ["high-protein", "high-carb", "quick"],
        ["gluten", "lactose"],
    ),
    (
        "Pancakes protéinés myrtilles",
        450,
        32,
        "petit-dejeuner",
        "internationale",
        "végétarien",
        15,
        [
            {"name": "Farine de blé complet", "quantity": 60, "unit": "g"},
            {"name": "Protéine en poudre vanille", "quantity": 30, "unit": "g"},
            {"name": "Œuf", "quantity": 2, "unit": "pièces"},
            {"name": "Myrtilles", "quantity": 80, "unit": "g"},
            {"name": "Lait", "quantity": 100, "unit": "ml"},
        ],
        "Mélanger farine, whey, œufs et lait. Cuire en pancakes. Garnir de myrtilles.",
        ["high-protein", "quick"],
        ["gluten", "oeuf", "lactose"],
    ),
    (
        "Tartines complètes jambon fromage blanc",
        400,
        28,
        "petit-dejeuner",
        "française",
        "omnivore",
        5,
        [
            {"name": "Pain complet", "quantity": 3, "unit": "tranches"},
            {"name": "Jambon blanc", "quantity": 60, "unit": "g"},
            {"name": "Fromage blanc 0%", "quantity": 50, "unit": "g"},
            {"name": "Tomate", "quantity": 80, "unit": "g"},
        ],
        "Toaster le pain. Tartiner de fromage blanc. Garnir de jambon et tomate.",
        ["high-protein", "low-fat", "quick"],
        ["gluten", "lactose"],
    ),
    (
        "Bol de riz au lait protéiné",
        500,
        28,
        "petit-dejeuner",
        "française",
        "végétarien",
        20,
        [
            {"name": "Riz rond", "quantity": 80, "unit": "g"},
            {"name": "Lait demi-écrémé", "quantity": 300, "unit": "ml"},
            {"name": "Protéine en poudre vanille", "quantity": 25, "unit": "g"},
            {"name": "Cannelle", "quantity": 2, "unit": "g"},
        ],
        "Cuire le riz dans le lait 15 min. Laisser tiédir, incorporer la whey. Saupoudrer de cannelle.",
        ["high-protein", "comfort"],
        ["lactose"],
    ),
    (
        "Wrap petit-déjeuner œufs et dinde",
        420,
        34,
        "petit-dejeuner",
        "internationale",
        "omnivore",
        10,
        [
            {"name": "Tortilla de blé", "quantity": 1, "unit": "pièce"},
            {"name": "Œuf", "quantity": 2, "unit": "pièces"},
            {"name": "Blanc de dinde", "quantity": 60, "unit": "g"},
            {"name": "Épinards", "quantity": 30, "unit": "g"},
        ],
        "Brouiller les œufs avec la dinde. Garnir la tortilla et rouler.",
        ["high-protein", "quick"],
        ["gluten", "oeuf"],
    ),
    (
        "Muesli maison yaourt et graines",
        440,
        20,
        "petit-dejeuner",
        "internationale",
        "végétarien",
        5,
        [
            {"name": "Muesli sans sucre", "quantity": 70, "unit": "g"},
            {"name": "Yaourt grec", "quantity": 150, "unit": "g"},
            {"name": "Graines de tournesol", "quantity": 15, "unit": "g"},
            {"name": "Miel", "quantity": 10, "unit": "g"},
        ],
        "Mélanger muesli et yaourt. Parsemer de graines et miel.",
        ["vegetarian", "quick", "high-fiber"],
        ["gluten", "lactose"],
    ),
    (
        "Omelette blanche champignons",
        280,
        30,
        "petit-dejeuner",
        "française",
        "omnivore",
        10,
        [
            {"name": "Blancs d'œufs", "quantity": 5, "unit": "pièces"},
            {"name": "Champignons de Paris", "quantity": 100, "unit": "g"},
            {"name": "Persil", "quantity": 5, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 5, "unit": "ml"},
        ],
        "Faire revenir les champignons. Battre les blancs d'œufs. Cuire l'omelette.",
        ["high-protein", "low-fat", "low-carb"],
        ["oeuf"],
    ),
    (
        "Smoothie bowl protéiné mangue",
        460,
        26,
        "petit-dejeuner",
        "internationale",
        "végétarien",
        5,
        [
            {"name": "Mangue surgelée", "quantity": 120, "unit": "g"},
            {"name": "Yaourt grec", "quantity": 150, "unit": "g"},
            {"name": "Protéine en poudre vanille", "quantity": 25, "unit": "g"},
            {"name": "Granola", "quantity": 30, "unit": "g"},
        ],
        "Mixer mangue et yaourt. Verser dans un bol. Garnir de granola et whey.",
        ["high-protein", "quick"],
        ["lactose", "gluten"],
    ),
    (
        "Gaufre protéinée au fromage blanc",
        380,
        26,
        "petit-dejeuner",
        "française",
        "végétarien",
        15,
        [
            {"name": "Farine complète", "quantity": 50, "unit": "g"},
            {"name": "Fromage blanc 0%", "quantity": 150, "unit": "g"},
            {"name": "Œuf", "quantity": 2, "unit": "pièces"},
            {"name": "Miel", "quantity": 10, "unit": "g"},
        ],
        "Mélanger farine, fromage blanc et œufs. Cuire au gaufrier. Napper de miel.",
        ["high-protein", "low-fat"],
        ["gluten", "oeuf", "lactose"],
    ),
    (
        "Bol açaí protéiné",
        500,
        24,
        "petit-dejeuner",
        "internationale",
        "vegan",
        5,
        [
            {"name": "Purée d'açaí surgelée", "quantity": 100, "unit": "g"},
            {"name": "Banane", "quantity": 1, "unit": "pièce"},
            {"name": "Protéine en poudre vanille", "quantity": 25, "unit": "g"},
            {"name": "Granola", "quantity": 40, "unit": "g"},
            {"name": "Lait d'amande", "quantity": 100, "unit": "ml"},
        ],
        "Mixer açaí, banane et lait d'amande. Verser dans un bol. Saupoudrer de granola et whey.",
        ["high-protein", "vegan-option"],
        ["gluten", "noix"],
    ),
    (
        "Œufs brouillés au saumon fumé",
        380,
        30,
        "petit-dejeuner",
        "internationale",
        "omnivore",
        10,
        [
            {"name": "Œufs", "quantity": 3, "unit": "pièces"},
            {"name": "Saumon fumé", "quantity": 50, "unit": "g"},
            {"name": "Pain complet", "quantity": 1, "unit": "tranche"},
            {"name": "Ciboulette", "quantity": 5, "unit": "g"},
        ],
        "Brouiller les œufs à feu doux. Servir avec le saumon fumé sur pain toasté.",
        ["high-protein", "omega3"],
        ["oeuf", "gluten", "poisson"],
    ),
    (
        "Granola bowl banane chocolat",
        520,
        18,
        "petit-dejeuner",
        "internationale",
        "végétarien",
        5,
        [
            {"name": "Granola", "quantity": 70, "unit": "g"},
            {"name": "Lait demi-écrémé", "quantity": 200, "unit": "ml"},
            {"name": "Banane", "quantity": 1, "unit": "pièce"},
            {"name": "Pépites de chocolat noir", "quantity": 15, "unit": "g"},
        ],
        "Verser le granola dans un bol. Ajouter le lait, la banane tranchée et le chocolat.",
        ["high-carb", "energy"],
        ["gluten", "lactose"],
    ),
    (
        "Tartine beurre de cacahuète et confiture",
        440,
        14,
        "petit-dejeuner",
        "internationale",
        "vegan",
        5,
        [
            {"name": "Pain complet", "quantity": 2, "unit": "tranches"},
            {"name": "Beurre de cacahuète", "quantity": 30, "unit": "g"},
            {"name": "Confiture de fraises", "quantity": 20, "unit": "g"},
        ],
        "Toaster le pain. Tartiner de beurre de cacahuète et confiture.",
        ["vegan", "quick", "energy"],
        ["gluten", "arachides"],
    ),
    (
        "Skyr myrtilles et miel",
        300,
        28,
        "petit-dejeuner",
        "internationale",
        "végétarien",
        3,
        [
            {"name": "Skyr nature", "quantity": 200, "unit": "g"},
            {"name": "Myrtilles", "quantity": 80, "unit": "g"},
            {"name": "Miel", "quantity": 15, "unit": "g"},
        ],
        "Verser le skyr dans un bol. Ajouter les myrtilles et le miel.",
        ["high-protein", "low-fat", "quick"],
        ["lactose"],
    ),
    (
        "Pudding chia protéiné overnight",
        420,
        24,
        "petit-dejeuner",
        "internationale",
        "végétarien",
        5,
        [
            {"name": "Graines de chia", "quantity": 30, "unit": "g"},
            {"name": "Lait demi-écrémé", "quantity": 250, "unit": "ml"},
            {"name": "Protéine en poudre vanille", "quantity": 25, "unit": "g"},
            {"name": "Fruits rouges", "quantity": 80, "unit": "g"},
        ],
        "Mélanger chia, lait et whey la veille. Réfrigérer une nuit. Garnir de fruits.",
        ["high-protein", "meal-prep"],
        ["lactose"],
    ),
    (
        "Croque-monsieur léger",
        420,
        28,
        "petit-dejeuner",
        "française",
        "omnivore",
        10,
        [
            {"name": "Pain de mie complet", "quantity": 2, "unit": "tranches"},
            {"name": "Jambon blanc", "quantity": 60, "unit": "g"},
            {"name": "Emmental râpé", "quantity": 25, "unit": "g"},
            {"name": "Lait", "quantity": 30, "unit": "ml"},
        ],
        "Assembler le croque-monsieur. Faire dorer au four 8 min à 200°C.",
        ["high-protein", "quick", "comfort"],
        ["gluten", "lactose"],
    ),
    (
        "Frittata courgette et feta",
        360,
        26,
        "petit-dejeuner",
        "méditerranéenne",
        "végétarien",
        20,
        [
            {"name": "Œufs", "quantity": 3, "unit": "pièces"},
            {"name": "Courgette", "quantity": 100, "unit": "g"},
            {"name": "Feta", "quantity": 40, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 5, "unit": "ml"},
        ],
        "Faire revenir la courgette. Verser les œufs battus. Émietter la feta. Cuire 10 min.",
        ["high-protein", "vegetarian", "low-carb"],
        ["oeuf", "lactose"],
    ),
    (
        "Bagel complet dinde et avocat",
        480,
        28,
        "petit-dejeuner",
        "internationale",
        "omnivore",
        5,
        [
            {"name": "Bagel complet", "quantity": 1, "unit": "pièce"},
            {"name": "Blanc de dinde", "quantity": 60, "unit": "g"},
            {"name": "Avocat", "quantity": 50, "unit": "g"},
            {"name": "Tomate", "quantity": 50, "unit": "g"},
        ],
        "Trancher le bagel. Garnir de dinde, avocat et tomate.",
        ["high-protein", "quick"],
        ["gluten"],
    ),
    (
        "Bol de quinoa sucré aux fruits",
        440,
        16,
        "petit-dejeuner",
        "internationale",
        "vegan",
        20,
        [
            {"name": "Quinoa", "quantity": 70, "unit": "g"},
            {"name": "Lait d'amande", "quantity": 200, "unit": "ml"},
            {"name": "Banane", "quantity": 1, "unit": "pièce"},
            {"name": "Miel", "quantity": 15, "unit": "g"},
            {"name": "Cannelle", "quantity": 2, "unit": "g"},
        ],
        "Cuire le quinoa dans le lait d'amande 15 min. Ajouter banane et miel.",
        ["vegan-option", "gluten-free", "high-carb"],
        ["noix"],
    ),
    (
        "Cottage cheese et pain complet",
        340,
        26,
        "petit-dejeuner",
        "internationale",
        "végétarien",
        3,
        [
            {"name": "Cottage cheese", "quantity": 200, "unit": "g"},
            {"name": "Pain complet", "quantity": 2, "unit": "tranches"},
            {"name": "Concombre", "quantity": 50, "unit": "g"},
        ],
        "Tartiner le pain de cottage cheese. Ajouter le concombre en rondelles.",
        ["high-protein", "low-fat", "quick"],
        ["lactose", "gluten"],
    ),
    # ── DÉJEUNER ────────────────────────────────────────────────────────────
    (
        "Poulet grillé riz et brocolis",
        550,
        45,
        "dejeuner",
        "internationale",
        "omnivore",
        25,
        [
            {"name": "Blanc de poulet", "quantity": 180, "unit": "g"},
            {"name": "Riz basmati", "quantity": 80, "unit": "g"},
            {"name": "Brocolis", "quantity": 150, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 10, "unit": "ml"},
        ],
        "Cuire le riz 12 min. Griller le poulet 6 min par face. Vapeur les brocolis. Assaisonner.",
        ["high-protein", "meal-prep", "balanced"],
        [],
    ),
    (
        "Salade niçoise au thon",
        450,
        35,
        "dejeuner",
        "méditerranéenne",
        "omnivore",
        15,
        [
            {"name": "Thon en conserve", "quantity": 120, "unit": "g"},
            {"name": "Œufs durs", "quantity": 2, "unit": "pièces"},
            {"name": "Tomates cerises", "quantity": 100, "unit": "g"},
            {"name": "Olives noires", "quantity": 30, "unit": "g"},
            {"name": "Haricots verts", "quantity": 80, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 15, "unit": "ml"},
        ],
        "Cuire les haricots verts 5 min. Assembler tous les ingrédients. Arroser d'huile.",
        ["high-protein", "mediterranean", "no-cook"],
        ["oeuf", "poisson"],
    ),
    (
        "Pâtes saumon sauce légère",
        580,
        38,
        "dejeuner",
        "italienne",
        "omnivore",
        20,
        [
            {"name": "Pâtes complètes", "quantity": 80, "unit": "g"},
            {"name": "Saumon frais", "quantity": 150, "unit": "g"},
            {"name": "Crème fraîche légère", "quantity": 50, "unit": "ml"},
            {"name": "Aneth", "quantity": 5, "unit": "g"},
            {"name": "Citron", "quantity": 0.5, "unit": "pièce"},
        ],
        "Cuire les pâtes al dente. Poêler le saumon 4 min. Mélanger avec crème et aneth.",
        ["high-protein", "omega3", "creamy"],
        ["gluten", "lactose", "poisson"],
    ),
    (
        "Bowl quinoa légumes rôtis",
        480,
        18,
        "dejeuner",
        "internationale",
        "végétarien",
        30,
        [
            {"name": "Quinoa", "quantity": 80, "unit": "g"},
            {"name": "Poivron rouge", "quantity": 100, "unit": "g"},
            {"name": "Courgette", "quantity": 100, "unit": "g"},
            {"name": "Pois chiches", "quantity": 80, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 15, "unit": "ml"},
        ],
        "Cuire le quinoa 15 min. Rôtir légumes et pois chiches 20 min à 200°C. Assembler.",
        ["vegetarian", "vegan", "meal-prep", "gluten-free"],
        [],
    ),
    (
        "Steak haché et patate douce",
        580,
        42,
        "dejeuner",
        "française",
        "omnivore",
        25,
        [
            {"name": "Steak haché 5%", "quantity": 180, "unit": "g"},
            {"name": "Patate douce", "quantity": 200, "unit": "g"},
            {"name": "Salade verte", "quantity": 50, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 10, "unit": "ml"},
        ],
        "Cuire la patate douce au four 25 min. Griller le steak 3 min par face. Servir avec salade.",
        ["high-protein", "balanced", "meal-prep"],
        [],
    ),
    (
        "Wrap thon et crudités",
        460,
        32,
        "dejeuner",
        "internationale",
        "omnivore",
        10,
        [
            {"name": "Tortilla de blé", "quantity": 1, "unit": "pièce"},
            {"name": "Thon en conserve", "quantity": 100, "unit": "g"},
            {"name": "Avocat", "quantity": 60, "unit": "g"},
            {"name": "Tomate", "quantity": 80, "unit": "g"},
            {"name": "Salade", "quantity": 30, "unit": "g"},
        ],
        "Égoutter le thon. Écraser l'avocat. Disposer tous les ingrédients sur la tortilla. Rouler.",
        ["high-protein", "quick", "no-cook"],
        ["gluten", "poisson"],
    ),
    (
        "Soupe lentilles corail épinards",
        380,
        20,
        "dejeuner",
        "méditerranéenne",
        "vegan",
        25,
        [
            {"name": "Lentilles corail", "quantity": 100, "unit": "g"},
            {"name": "Épinards", "quantity": 80, "unit": "g"},
            {"name": "Tomates pelées", "quantity": 200, "unit": "g"},
            {"name": "Oignon", "quantity": 1, "unit": "pièce"},
            {"name": "Cumin", "quantity": 3, "unit": "g"},
        ],
        "Faire revenir l'oignon. Ajouter lentilles, tomates et bouillon. Cuire 20 min. Ajouter épinards.",
        ["vegan", "high-fiber", "budget", "gluten-free"],
        [],
    ),
    (
        "Taboulé et poulet grillé",
        480,
        36,
        "dejeuner",
        "méditerranéenne",
        "omnivore",
        20,
        [
            {"name": "Semoule fine", "quantity": 80, "unit": "g"},
            {"name": "Blanc de poulet", "quantity": 150, "unit": "g"},
            {"name": "Concombre", "quantity": 80, "unit": "g"},
            {"name": "Tomates", "quantity": 80, "unit": "g"},
            {"name": "Persil", "quantity": 20, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 10, "unit": "ml"},
        ],
        "Hydrater la semoule. Griller le poulet. Mélanger semoule, légumes et persil. Servir ensemble.",
        ["high-protein", "mediterranean", "fresh"],
        ["gluten"],
    ),
    (
        "Risotto champignons parmesan",
        520,
        16,
        "dejeuner",
        "italienne",
        "végétarien",
        30,
        [
            {"name": "Riz arborio", "quantity": 80, "unit": "g"},
            {"name": "Champignons de Paris", "quantity": 150, "unit": "g"},
            {"name": "Parmesan", "quantity": 30, "unit": "g"},
            {"name": "Oignon", "quantity": 1, "unit": "pièce"},
            {"name": "Bouillon de légumes", "quantity": 400, "unit": "ml"},
        ],
        "Faire revenir oignon et champignons. Ajouter riz, incorporer le bouillon louche par louche.",
        ["vegetarian", "comfort", "italian"],
        ["lactose", "gluten"],
    ),
    (
        "Escalope dinde haricots verts",
        450,
        44,
        "dejeuner",
        "française",
        "omnivore",
        20,
        [
            {"name": "Escalope de dinde", "quantity": 200, "unit": "g"},
            {"name": "Haricots verts", "quantity": 150, "unit": "g"},
            {"name": "Moutarde de Dijon", "quantity": 15, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 10, "unit": "ml"},
        ],
        "Badigeonner la dinde de moutarde. Griller 5 min par face. Cuire les haricots verts à la vapeur.",
        ["high-protein", "low-fat", "french"],
        [],
    ),
    # ── DÉJEUNER (batch 2) ──────────────────────────────────────────────────
    (
        "Bowl poulet quinoa edamame",
        580,
        48,
        "dejeuner",
        "asiatique",
        "omnivore",
        25,
        [
            {"name": "Blanc de poulet", "quantity": 180, "unit": "g"},
            {"name": "Quinoa", "quantity": 80, "unit": "g"},
            {"name": "Edamame", "quantity": 60, "unit": "g"},
            {"name": "Sauce soja", "quantity": 10, "unit": "ml"},
        ],
        "Cuire le quinoa. Griller le poulet. Assembler le bowl avec edamame et sauce soja.",
        ["high-protein", "asian", "meal-prep"],
        ["soja"],
    ),
    (
        "Sauté de bœuf et légumes au wok",
        550,
        42,
        "dejeuner",
        "asiatique",
        "omnivore",
        20,
        [
            {"name": "Rumsteck", "quantity": 180, "unit": "g"},
            {"name": "Brocolis", "quantity": 100, "unit": "g"},
            {"name": "Poivron rouge", "quantity": 80, "unit": "g"},
            {"name": "Riz basmati", "quantity": 80, "unit": "g"},
            {"name": "Sauce soja", "quantity": 15, "unit": "ml"},
        ],
        "Faire sauter le bœuf émincé au wok. Ajouter les légumes. Servir avec riz.",
        ["high-protein", "asian", "quick"],
        ["soja"],
    ),
    (
        "Bowl thon quinoa avocat",
        520,
        38,
        "dejeuner",
        "internationale",
        "omnivore",
        15,
        [
            {"name": "Thon en conserve", "quantity": 120, "unit": "g"},
            {"name": "Quinoa", "quantity": 80, "unit": "g"},
            {"name": "Avocat", "quantity": 60, "unit": "g"},
            {"name": "Tomates cerises", "quantity": 80, "unit": "g"},
            {"name": "Citron", "quantity": 0.5, "unit": "pièce"},
        ],
        "Cuire le quinoa. Assembler avec thon, avocat et tomates. Arroser de citron.",
        ["high-protein", "omega3", "no-cook"],
        ["poisson"],
    ),
    (
        "Gratin de poulet brocoli",
        580,
        50,
        "dejeuner",
        "française",
        "omnivore",
        30,
        [
            {"name": "Blanc de poulet", "quantity": 200, "unit": "g"},
            {"name": "Brocolis", "quantity": 200, "unit": "g"},
            {"name": "Emmental râpé", "quantity": 30, "unit": "g"},
            {"name": "Crème légère", "quantity": 50, "unit": "ml"},
        ],
        "Découper le poulet. Assembler avec brocolis dans un plat. Napper de crème et fromage. Gratiner 20 min.",
        ["high-protein", "comfort"],
        ["lactose"],
    ),
    (
        "Poké bowl saumon riz complet",
        560,
        36,
        "dejeuner",
        "asiatique",
        "omnivore",
        20,
        [
            {"name": "Saumon frais", "quantity": 150, "unit": "g"},
            {"name": "Riz complet", "quantity": 80, "unit": "g"},
            {"name": "Concombre", "quantity": 60, "unit": "g"},
            {"name": "Avocat", "quantity": 50, "unit": "g"},
            {"name": "Sauce soja", "quantity": 10, "unit": "ml"},
        ],
        "Cuire le riz. Trancher le saumon. Assembler le poké bowl avec les légumes.",
        ["high-protein", "omega3", "asian"],
        ["poisson", "soja"],
    ),
    (
        "Chili con carne léger",
        520,
        38,
        "dejeuner",
        "mexicaine",
        "omnivore",
        30,
        [
            {"name": "Bœuf haché 5%", "quantity": 150, "unit": "g"},
            {"name": "Haricots rouges", "quantity": 100, "unit": "g"},
            {"name": "Tomates concassées", "quantity": 200, "unit": "g"},
            {"name": "Oignon", "quantity": 1, "unit": "pièce"},
            {"name": "Cumin", "quantity": 3, "unit": "g"},
        ],
        "Faire revenir le bœuf et l'oignon. Ajouter haricots, tomates et cumin. Mijoter 20 min.",
        ["high-protein", "high-fiber", "budget"],
        [],
    ),
    (
        "Salade de poulet grillé césar",
        480,
        40,
        "dejeuner",
        "internationale",
        "omnivore",
        15,
        [
            {"name": "Blanc de poulet", "quantity": 180, "unit": "g"},
            {"name": "Salade romaine", "quantity": 100, "unit": "g"},
            {"name": "Parmesan", "quantity": 20, "unit": "g"},
            {"name": "Croûtons", "quantity": 30, "unit": "g"},
            {"name": "Sauce césar légère", "quantity": 20, "unit": "ml"},
        ],
        "Griller le poulet. Assembler la salade avec romaine, parmesan et croûtons.",
        ["high-protein", "fresh"],
        ["lactose", "gluten"],
    ),
    (
        "Curry de poulet aux lentilles",
        560,
        44,
        "dejeuner",
        "asiatique",
        "omnivore",
        30,
        [
            {"name": "Blanc de poulet", "quantity": 180, "unit": "g"},
            {"name": "Lentilles corail", "quantity": 80, "unit": "g"},
            {"name": "Lait de coco", "quantity": 80, "unit": "ml"},
            {"name": "Curry en poudre", "quantity": 5, "unit": "g"},
            {"name": "Oignon", "quantity": 1, "unit": "pièce"},
        ],
        "Faire revenir poulet et oignon. Ajouter lentilles, curry et lait de coco. Mijoter 20 min.",
        ["high-protein", "spicy", "gluten-free"],
        [],
    ),
    (
        "Pad thaï poulet",
        540,
        36,
        "dejeuner",
        "asiatique",
        "omnivore",
        25,
        [
            {"name": "Nouilles de riz", "quantity": 80, "unit": "g"},
            {"name": "Blanc de poulet", "quantity": 150, "unit": "g"},
            {"name": "Germes de soja", "quantity": 50, "unit": "g"},
            {"name": "Cacahuètes concassées", "quantity": 15, "unit": "g"},
            {"name": "Sauce soja", "quantity": 15, "unit": "ml"},
            {"name": "Citron vert", "quantity": 0.5, "unit": "pièce"},
        ],
        "Cuire les nouilles. Faire sauter le poulet. Assembler avec germes de soja et sauce.",
        ["high-protein", "asian"],
        ["arachides", "soja"],
    ),
    (
        "Assiette dinde patate douce épinards",
        520,
        44,
        "dejeuner",
        "internationale",
        "omnivore",
        25,
        [
            {"name": "Escalope de dinde", "quantity": 200, "unit": "g"},
            {"name": "Patate douce", "quantity": 180, "unit": "g"},
            {"name": "Épinards frais", "quantity": 80, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 5, "unit": "ml"},
        ],
        "Cuire la patate douce au four. Griller la dinde. Faire revenir les épinards.",
        ["high-protein", "low-fat", "balanced"],
        [],
    ),
    (
        "Spaghetti bolognaise protéinée",
        580,
        40,
        "dejeuner",
        "italienne",
        "omnivore",
        25,
        [
            {"name": "Pâtes complètes", "quantity": 80, "unit": "g"},
            {"name": "Bœuf haché 5%", "quantity": 150, "unit": "g"},
            {"name": "Tomates concassées", "quantity": 200, "unit": "g"},
            {"name": "Oignon", "quantity": 1, "unit": "pièce"},
            {"name": "Parmesan", "quantity": 15, "unit": "g"},
        ],
        "Faire revenir le bœuf haché et l'oignon. Ajouter tomates, mijoter. Servir sur pâtes.",
        ["high-protein", "italian", "comfort"],
        ["gluten", "lactose"],
    ),
    (
        "Bol mexicain poulet haricots",
        560,
        42,
        "dejeuner",
        "mexicaine",
        "omnivore",
        20,
        [
            {"name": "Blanc de poulet", "quantity": 180, "unit": "g"},
            {"name": "Haricots noirs", "quantity": 80, "unit": "g"},
            {"name": "Riz basmati", "quantity": 60, "unit": "g"},
            {"name": "Poivron", "quantity": 80, "unit": "g"},
            {"name": "Avocat", "quantity": 40, "unit": "g"},
        ],
        "Griller le poulet. Cuire le riz. Assembler en bowl avec haricots et poivron.",
        ["high-protein", "balanced"],
        [],
    ),
    (
        "Couscous poulet et légumes",
        560,
        40,
        "dejeuner",
        "méditerranéenne",
        "omnivore",
        30,
        [
            {"name": "Semoule de couscous", "quantity": 80, "unit": "g"},
            {"name": "Blanc de poulet", "quantity": 180, "unit": "g"},
            {"name": "Courgette", "quantity": 100, "unit": "g"},
            {"name": "Carotte", "quantity": 80, "unit": "g"},
            {"name": "Pois chiches", "quantity": 60, "unit": "g"},
        ],
        "Cuire le couscous. Griller le poulet. Mijoter les légumes. Assembler.",
        ["high-protein", "mediterranean", "balanced"],
        ["gluten"],
    ),
    (
        "Tartare de saumon et riz",
        500,
        34,
        "dejeuner",
        "asiatique",
        "omnivore",
        15,
        [
            {"name": "Saumon frais", "quantity": 160, "unit": "g"},
            {"name": "Riz vinaigré", "quantity": 80, "unit": "g"},
            {"name": "Concombre", "quantity": 60, "unit": "g"},
            {"name": "Sauce soja", "quantity": 10, "unit": "ml"},
            {"name": "Sésame", "quantity": 5, "unit": "g"},
        ],
        "Découper le saumon en dés. Assaisonner de soja et sésame. Servir avec riz et concombre.",
        ["high-protein", "omega3", "asian"],
        ["poisson", "soja", "sesame"],
    ),
    (
        "Poulet tikka masala et riz",
        580,
        42,
        "dejeuner",
        "asiatique",
        "omnivore",
        30,
        [
            {"name": "Blanc de poulet", "quantity": 180, "unit": "g"},
            {"name": "Riz basmati", "quantity": 80, "unit": "g"},
            {"name": "Yaourt nature", "quantity": 50, "unit": "g"},
            {"name": "Tomates concassées", "quantity": 150, "unit": "g"},
            {"name": "Épices tandoori", "quantity": 5, "unit": "g"},
        ],
        "Mariner le poulet dans le yaourt et épices. Cuire avec les tomates. Servir avec riz.",
        ["high-protein", "spicy"],
        ["lactose"],
    ),
    (
        "Salade de lentilles au poulet",
        480,
        40,
        "dejeuner",
        "française",
        "omnivore",
        20,
        [
            {"name": "Lentilles vertes", "quantity": 100, "unit": "g"},
            {"name": "Blanc de poulet", "quantity": 150, "unit": "g"},
            {"name": "Carotte", "quantity": 60, "unit": "g"},
            {"name": "Échalote", "quantity": 1, "unit": "pièce"},
            {"name": "Vinaigre balsamique", "quantity": 10, "unit": "ml"},
        ],
        "Cuire les lentilles. Griller le poulet. Assembler en salade tiède.",
        ["high-protein", "high-fiber", "french"],
        [],
    ),
    (
        "Fajitas de bœuf",
        540,
        38,
        "dejeuner",
        "mexicaine",
        "omnivore",
        20,
        [
            {"name": "Rumsteck", "quantity": 160, "unit": "g"},
            {"name": "Tortilla de blé", "quantity": 2, "unit": "pièces"},
            {"name": "Poivron", "quantity": 100, "unit": "g"},
            {"name": "Oignon", "quantity": 80, "unit": "g"},
            {"name": "Fromage râpé", "quantity": 20, "unit": "g"},
        ],
        "Faire sauter le bœuf avec poivrons et oignons. Garnir les tortillas.",
        ["high-protein", "quick"],
        ["gluten", "lactose"],
    ),
    (
        "Hachis parmentier de dinde",
        520,
        40,
        "dejeuner",
        "française",
        "omnivore",
        35,
        [
            {"name": "Dinde hachée", "quantity": 180, "unit": "g"},
            {"name": "Pomme de terre", "quantity": 200, "unit": "g"},
            {"name": "Lait demi-écrémé", "quantity": 50, "unit": "ml"},
            {"name": "Oignon", "quantity": 1, "unit": "pièce"},
            {"name": "Emmental râpé", "quantity": 20, "unit": "g"},
        ],
        "Préparer la purée. Faire revenir la dinde hachée. Superposer et gratiner.",
        ["high-protein", "comfort", "french"],
        ["lactose"],
    ),
    (
        "Salade de quinoa aux crevettes",
        460,
        36,
        "dejeuner",
        "méditerranéenne",
        "omnivore",
        20,
        [
            {"name": "Quinoa", "quantity": 80, "unit": "g"},
            {"name": "Crevettes décortiquées", "quantity": 150, "unit": "g"},
            {"name": "Concombre", "quantity": 80, "unit": "g"},
            {"name": "Tomates cerises", "quantity": 80, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 10, "unit": "ml"},
        ],
        "Cuire le quinoa. Poêler les crevettes. Assembler la salade.",
        ["high-protein", "gluten-free", "fresh"],
        ["crustaces"],
    ),
    (
        "Tofu sauté aux légumes et riz",
        460,
        24,
        "dejeuner",
        "asiatique",
        "vegan",
        20,
        [
            {"name": "Tofu ferme", "quantity": 200, "unit": "g"},
            {"name": "Riz basmati", "quantity": 80, "unit": "g"},
            {"name": "Brocolis", "quantity": 100, "unit": "g"},
            {"name": "Sauce soja", "quantity": 15, "unit": "ml"},
            {"name": "Huile de sésame", "quantity": 5, "unit": "ml"},
        ],
        "Émincer et poêler le tofu. Faire sauter les brocolis. Servir avec riz.",
        ["vegan", "high-protein", "asian"],
        ["soja", "sesame"],
    ),
    # ── DÎNER ───────────────────────────────────────────────────────────────
    (
        "Saumon vapeur et haricots verts",
        400,
        38,
        "diner",
        "française",
        "omnivore",
        15,
        [
            {"name": "Pavé de saumon", "quantity": 180, "unit": "g"},
            {"name": "Haricots verts", "quantity": 150, "unit": "g"},
            {"name": "Citron", "quantity": 0.5, "unit": "pièce"},
            {"name": "Aneth", "quantity": 5, "unit": "g"},
        ],
        "Cuire le saumon vapeur 10 min. Cuire haricots verts 5 min. Servir avec citron et aneth.",
        ["high-protein", "omega3", "light", "gluten-free"],
        ["poisson"],
    ),
    (
        "Poulet curry et riz basmati",
        560,
        40,
        "diner",
        "asiatique",
        "omnivore",
        30,
        [
            {"name": "Blanc de poulet", "quantity": 180, "unit": "g"},
            {"name": "Riz basmati", "quantity": 80, "unit": "g"},
            {"name": "Lait de coco", "quantity": 100, "unit": "ml"},
            {"name": "Curry en poudre", "quantity": 5, "unit": "g"},
            {"name": "Oignon", "quantity": 1, "unit": "pièce"},
        ],
        "Faire revenir poulet et oignon. Ajouter curry et lait de coco. Mijoter 15 min. Servir avec riz.",
        ["high-protein", "spicy", "asian"],
        ["lactose"],
    ),
    (
        "Ratatouille et poulet rôti",
        380,
        32,
        "diner",
        "française",
        "omnivore",
        40,
        [
            {"name": "Blanc de poulet", "quantity": 150, "unit": "g"},
            {"name": "Courgette", "quantity": 100, "unit": "g"},
            {"name": "Aubergine", "quantity": 100, "unit": "g"},
            {"name": "Poivron", "quantity": 80, "unit": "g"},
            {"name": "Tomates concassées", "quantity": 150, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 10, "unit": "ml"},
        ],
        "Rôtir le poulet 20 min. Faire mijoter les légumes en ratatouille 25 min. Servir ensemble.",
        ["high-protein", "mediterranean", "low-carb", "gluten-free"],
        [],
    ),
    (
        "Cabillaud en papillote légumes",
        340,
        38,
        "diner",
        "française",
        "omnivore",
        20,
        [
            {"name": "Filet de cabillaud", "quantity": 200, "unit": "g"},
            {"name": "Courgette", "quantity": 100, "unit": "g"},
            {"name": "Tomates cerises", "quantity": 80, "unit": "g"},
            {"name": "Citron", "quantity": 0.5, "unit": "pièce"},
            {"name": "Huile d'olive", "quantity": 10, "unit": "ml"},
        ],
        "Placer le cabillaud et légumes sur papier cuisson. Citronner. Fermer et cuire 15 min à 180°C.",
        ["high-protein", "light", "gluten-free", "omega3"],
        ["poisson"],
    ),
    (
        "Curry de pois chiches et épinards",
        420,
        16,
        "diner",
        "asiatique",
        "vegan",
        25,
        [
            {"name": "Pois chiches", "quantity": 150, "unit": "g"},
            {"name": "Épinards", "quantity": 100, "unit": "g"},
            {"name": "Lait de coco", "quantity": 100, "unit": "ml"},
            {"name": "Tomates concassées", "quantity": 150, "unit": "g"},
            {"name": "Curry", "quantity": 5, "unit": "g"},
        ],
        "Faire revenir les épices. Ajouter pois chiches et tomates. Incorporer lait de coco 10 min.",
        ["vegan", "high-fiber", "gluten-free", "budget"],
        [],
    ),
    (
        "Omelette poireaux et chèvre",
        360,
        24,
        "diner",
        "française",
        "végétarien",
        15,
        [
            {"name": "Œufs", "quantity": 3, "unit": "pièces"},
            {"name": "Poireau", "quantity": 100, "unit": "g"},
            {"name": "Fromage de chèvre", "quantity": 50, "unit": "g"},
            {"name": "Beurre", "quantity": 10, "unit": "g"},
        ],
        "Faire suer le poireau au beurre 5 min. Battre les œufs, verser sur les poireaux. Ajouter chèvre.",
        ["vegetarian", "low-carb", "quick"],
        ["oeuf", "lactose"],
    ),
    (
        "Velouté de potiron",
        240,
        6,
        "diner",
        "française",
        "vegan",
        30,
        [
            {"name": "Potiron", "quantity": 400, "unit": "g"},
            {"name": "Oignon", "quantity": 1, "unit": "pièce"},
            {"name": "Bouillon de légumes", "quantity": 500, "unit": "ml"},
            {"name": "Crème de coco", "quantity": 50, "unit": "ml"},
            {"name": "Muscade", "quantity": 1, "unit": "g"},
        ],
        "Faire revenir oignon. Ajouter potiron et bouillon. Cuire 20 min. Mixer. Ajouter crème de coco.",
        ["vegan", "light", "comfort", "gluten-free"],
        [],
    ),
    (
        "Wok crevettes légumes",
        380,
        32,
        "diner",
        "asiatique",
        "omnivore",
        15,
        [
            {"name": "Crevettes décortiquées", "quantity": 150, "unit": "g"},
            {"name": "Brocolis", "quantity": 100, "unit": "g"},
            {"name": "Poivron rouge", "quantity": 80, "unit": "g"},
            {"name": "Sauce soja", "quantity": 15, "unit": "ml"},
            {"name": "Huile de sésame", "quantity": 10, "unit": "ml"},
            {"name": "Gingembre", "quantity": 5, "unit": "g"},
        ],
        "Chauffer wok très chaud. Sauter les crevettes 3 min. Ajouter légumes et sauce. Cuire 5 min.",
        ["high-protein", "asian", "quick", "low-carb"],
        ["crustaces", "soja"],
    ),
    (
        "Escalope dinde champignons",
        360,
        38,
        "diner",
        "française",
        "omnivore",
        20,
        [
            {"name": "Escalope de dinde", "quantity": 200, "unit": "g"},
            {"name": "Champignons de Paris", "quantity": 150, "unit": "g"},
            {"name": "Échalote", "quantity": 1, "unit": "pièce"},
            {"name": "Crème légère", "quantity": 50, "unit": "ml"},
        ],
        "Poêler la dinde 5 min par face. Faire revenir champignons et échalote. Déglacer à la crème.",
        ["high-protein", "french", "creamy"],
        ["lactose"],
    ),
    (
        "Lentilles et saumon poché",
        480,
        40,
        "diner",
        "française",
        "omnivore",
        25,
        [
            {"name": "Lentilles vertes", "quantity": 100, "unit": "g"},
            {"name": "Pavé de saumon", "quantity": 150, "unit": "g"},
            {"name": "Carotte", "quantity": 80, "unit": "g"},
            {"name": "Thym", "quantity": 2, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 10, "unit": "ml"},
        ],
        "Cuire les lentilles avec carottes et thym 20 min. Pocher le saumon 8 min. Servir ensemble.",
        ["high-protein", "omega3", "iron-rich", "gluten-free"],
        ["poisson"],
    ),
    # ── DÎNER (batch 2) ──────────────────────────────────────────────────────
    (
        "Poisson blanc riz et courgettes",
        400,
        40,
        "diner",
        "française",
        "omnivore",
        20,
        [
            {"name": "Filet de colin", "quantity": 200, "unit": "g"},
            {"name": "Riz basmati", "quantity": 70, "unit": "g"},
            {"name": "Courgette", "quantity": 120, "unit": "g"},
            {"name": "Citron", "quantity": 0.5, "unit": "pièce"},
        ],
        "Cuire le poisson au four 12 min. Cuire le riz. Poêler les courgettes.",
        ["high-protein", "low-fat", "gluten-free"],
        ["poisson"],
    ),
    (
        "Escalope de dinde purée de brocoli",
        420,
        44,
        "diner",
        "française",
        "omnivore",
        25,
        [
            {"name": "Escalope de dinde", "quantity": 200, "unit": "g"},
            {"name": "Brocolis", "quantity": 200, "unit": "g"},
            {"name": "Lait demi-écrémé", "quantity": 50, "unit": "ml"},
            {"name": "Muscade", "quantity": 1, "unit": "g"},
        ],
        "Griller la dinde. Cuire et mixer les brocolis en purée avec le lait.",
        ["high-protein", "low-fat", "low-carb"],
        ["lactose"],
    ),
    (
        "Soupe protéinée poulet et légumes",
        380,
        36,
        "diner",
        "française",
        "omnivore",
        25,
        [
            {"name": "Blanc de poulet", "quantity": 150, "unit": "g"},
            {"name": "Carotte", "quantity": 80, "unit": "g"},
            {"name": "Poireau", "quantity": 80, "unit": "g"},
            {"name": "Pomme de terre", "quantity": 100, "unit": "g"},
            {"name": "Bouillon de poule", "quantity": 400, "unit": "ml"},
        ],
        "Cuire le poulet avec les légumes dans le bouillon 20 min. Servir chaud.",
        ["high-protein", "comfort", "light"],
        [],
    ),
    (
        "Tilapia grillé et quinoa",
        420,
        40,
        "diner",
        "internationale",
        "omnivore",
        20,
        [
            {"name": "Filet de tilapia", "quantity": 200, "unit": "g"},
            {"name": "Quinoa", "quantity": 70, "unit": "g"},
            {"name": "Tomates cerises", "quantity": 80, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 5, "unit": "ml"},
        ],
        "Griller le tilapia. Cuire le quinoa. Assembler avec tomates cerises.",
        ["high-protein", "gluten-free", "low-fat"],
        ["poisson"],
    ),
    (
        "Blanquette de poulet légère",
        440,
        38,
        "diner",
        "française",
        "omnivore",
        35,
        [
            {"name": "Blanc de poulet", "quantity": 180, "unit": "g"},
            {"name": "Carotte", "quantity": 100, "unit": "g"},
            {"name": "Champignons", "quantity": 80, "unit": "g"},
            {"name": "Crème légère", "quantity": 40, "unit": "ml"},
            {"name": "Riz basmati", "quantity": 60, "unit": "g"},
        ],
        "Pocher le poulet avec les légumes. Lier à la crème légère. Servir avec riz.",
        ["high-protein", "french", "comfort"],
        ["lactose"],
    ),
    (
        "Steak de thon et haricots verts",
        380,
        42,
        "diner",
        "internationale",
        "omnivore",
        15,
        [
            {"name": "Steak de thon", "quantity": 200, "unit": "g"},
            {"name": "Haricots verts", "quantity": 150, "unit": "g"},
            {"name": "Citron", "quantity": 0.5, "unit": "pièce"},
            {"name": "Huile d'olive", "quantity": 5, "unit": "ml"},
        ],
        "Saisir le thon 2 min par face. Cuire les haricots verts à la vapeur.",
        ["high-protein", "omega3", "quick", "gluten-free"],
        ["poisson"],
    ),
    (
        "Poulet rôti et ratatouille niçoise",
        420,
        36,
        "diner",
        "française",
        "omnivore",
        40,
        [
            {"name": "Cuisse de poulet", "quantity": 180, "unit": "g"},
            {"name": "Courgette", "quantity": 100, "unit": "g"},
            {"name": "Aubergine", "quantity": 80, "unit": "g"},
            {"name": "Tomates", "quantity": 100, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 10, "unit": "ml"},
        ],
        "Rôtir le poulet au four. Cuire la ratatouille à la poêle.",
        ["high-protein", "mediterranean"],
        [],
    ),
    (
        "Filet mignon porc et purée",
        480,
        38,
        "diner",
        "française",
        "omnivore",
        30,
        [
            {"name": "Filet mignon de porc", "quantity": 180, "unit": "g"},
            {"name": "Pomme de terre", "quantity": 200, "unit": "g"},
            {"name": "Lait demi-écrémé", "quantity": 50, "unit": "ml"},
            {"name": "Moutarde de Dijon", "quantity": 10, "unit": "g"},
        ],
        "Rôtir le filet mignon 20 min. Préparer la purée. Servir avec moutarde.",
        ["high-protein", "french", "comfort"],
        ["lactose"],
    ),
    (
        "Bowl poké au tofu",
        400,
        22,
        "diner",
        "asiatique",
        "vegan",
        20,
        [
            {"name": "Tofu ferme", "quantity": 200, "unit": "g"},
            {"name": "Riz vinaigré", "quantity": 80, "unit": "g"},
            {"name": "Avocat", "quantity": 50, "unit": "g"},
            {"name": "Concombre", "quantity": 60, "unit": "g"},
            {"name": "Sauce soja", "quantity": 10, "unit": "ml"},
        ],
        "Mariner et poêler le tofu. Assembler le bowl avec riz et légumes.",
        ["vegan", "asian", "balanced"],
        ["soja"],
    ),
    (
        "Gratin de courgettes au poulet",
        420,
        40,
        "diner",
        "française",
        "omnivore",
        30,
        [
            {"name": "Blanc de poulet", "quantity": 180, "unit": "g"},
            {"name": "Courgette", "quantity": 200, "unit": "g"},
            {"name": "Crème légère", "quantity": 40, "unit": "ml"},
            {"name": "Emmental râpé", "quantity": 25, "unit": "g"},
        ],
        "Disposer poulet et courgettes émincées. Napper de crème. Gratiner 20 min.",
        ["high-protein", "low-carb"],
        ["lactose"],
    ),
    (
        "Tartare de bœuf et salade",
        400,
        36,
        "diner",
        "française",
        "omnivore",
        15,
        [
            {"name": "Bœuf haché frais", "quantity": 180, "unit": "g"},
            {"name": "Jaune d'œuf", "quantity": 1, "unit": "pièce"},
            {"name": "Câpres", "quantity": 10, "unit": "g"},
            {"name": "Salade verte", "quantity": 80, "unit": "g"},
            {"name": "Moutarde", "quantity": 5, "unit": "g"},
        ],
        "Assaisonner le bœuf haché cru avec câpres, moutarde et jaune d'œuf.",
        ["high-protein", "low-carb", "raw"],
        ["oeuf"],
    ),
    (
        "Daurade en croûte de sel et légumes",
        360,
        38,
        "diner",
        "méditerranéenne",
        "omnivore",
        35,
        [
            {"name": "Filet de daurade", "quantity": 200, "unit": "g"},
            {"name": "Fenouil", "quantity": 100, "unit": "g"},
            {"name": "Tomates cerises", "quantity": 80, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 5, "unit": "ml"},
        ],
        "Cuire la daurade au four avec le fenouil et les tomates.",
        ["high-protein", "low-fat", "mediterranean", "gluten-free"],
        ["poisson"],
    ),
    (
        "Poulet teriyaki et riz complet",
        500,
        38,
        "diner",
        "asiatique",
        "omnivore",
        25,
        [
            {"name": "Blanc de poulet", "quantity": 180, "unit": "g"},
            {"name": "Riz complet", "quantity": 80, "unit": "g"},
            {"name": "Sauce teriyaki", "quantity": 20, "unit": "ml"},
            {"name": "Brocolis", "quantity": 100, "unit": "g"},
        ],
        "Mariner le poulet dans la sauce teriyaki. Griller. Servir avec riz et brocolis.",
        ["high-protein", "asian"],
        ["soja"],
    ),
    (
        "Galettes de lentilles et salade",
        380,
        22,
        "diner",
        "française",
        "vegan",
        25,
        [
            {"name": "Lentilles corail", "quantity": 120, "unit": "g"},
            {"name": "Oignon", "quantity": 1, "unit": "pièce"},
            {"name": "Cumin", "quantity": 3, "unit": "g"},
            {"name": "Salade verte", "quantity": 80, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 10, "unit": "ml"},
        ],
        "Mixer les lentilles cuites avec l'oignon et le cumin. Former des galettes et poêler.",
        ["vegan", "high-fiber", "budget"],
        [],
    ),
    (
        "Blanc de poulet grillé asperges",
        340,
        42,
        "diner",
        "française",
        "omnivore",
        15,
        [
            {"name": "Blanc de poulet", "quantity": 200, "unit": "g"},
            {"name": "Asperges vertes", "quantity": 150, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 5, "unit": "ml"},
            {"name": "Citron", "quantity": 0.5, "unit": "pièce"},
        ],
        "Griller le poulet et les asperges. Arroser de citron.",
        ["high-protein", "low-carb", "low-fat", "quick"],
        [],
    ),
    (
        "Papillote de cabillaud aux poireaux",
        320,
        36,
        "diner",
        "française",
        "omnivore",
        20,
        [
            {"name": "Filet de cabillaud", "quantity": 200, "unit": "g"},
            {"name": "Poireau", "quantity": 120, "unit": "g"},
            {"name": "Citron", "quantity": 0.5, "unit": "pièce"},
            {"name": "Crème légère", "quantity": 30, "unit": "ml"},
        ],
        "Placer cabillaud et poireaux émincés en papillote. Ajouter crème et citron. Cuire 15 min.",
        ["high-protein", "light", "low-carb"],
        ["poisson", "lactose"],
    ),
    (
        "Poulet basquaise",
        460,
        36,
        "diner",
        "française",
        "omnivore",
        35,
        [
            {"name": "Cuisse de poulet", "quantity": 180, "unit": "g"},
            {"name": "Poivron rouge", "quantity": 100, "unit": "g"},
            {"name": "Poivron vert", "quantity": 80, "unit": "g"},
            {"name": "Tomates concassées", "quantity": 150, "unit": "g"},
            {"name": "Oignon", "quantity": 1, "unit": "pièce"},
        ],
        "Faire revenir le poulet. Ajouter les poivrons, oignon et tomates. Mijoter 25 min.",
        ["high-protein", "mediterranean", "comfort"],
        [],
    ),
    (
        "Saumon laqué au miel et brocolis",
        440,
        36,
        "diner",
        "asiatique",
        "omnivore",
        20,
        [
            {"name": "Pavé de saumon", "quantity": 150, "unit": "g"},
            {"name": "Miel", "quantity": 15, "unit": "g"},
            {"name": "Sauce soja", "quantity": 10, "unit": "ml"},
            {"name": "Brocolis", "quantity": 150, "unit": "g"},
        ],
        "Laquer le saumon de miel et soja. Cuire au four 12 min. Vapeur les brocolis.",
        ["high-protein", "omega3", "asian"],
        ["poisson", "soja"],
    ),
    (
        "Salade tiède de poulet et patate douce",
        440,
        36,
        "diner",
        "internationale",
        "omnivore",
        25,
        [
            {"name": "Blanc de poulet", "quantity": 160, "unit": "g"},
            {"name": "Patate douce", "quantity": 150, "unit": "g"},
            {"name": "Épinards frais", "quantity": 60, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 5, "unit": "ml"},
            {"name": "Vinaigre balsamique", "quantity": 10, "unit": "ml"},
        ],
        "Rôtir le poulet et la patate douce. Assembler avec les épinards en salade tiède.",
        ["high-protein", "balanced"],
        [],
    ),
    (
        "Crevettes sautées ail et courgettes",
        320,
        34,
        "diner",
        "méditerranéenne",
        "omnivore",
        15,
        [
            {"name": "Crevettes décortiquées", "quantity": 180, "unit": "g"},
            {"name": "Courgette", "quantity": 150, "unit": "g"},
            {"name": "Ail", "quantity": 2, "unit": "pièces"},
            {"name": "Huile d'olive", "quantity": 10, "unit": "ml"},
            {"name": "Persil", "quantity": 5, "unit": "g"},
        ],
        "Faire sauter les crevettes avec l'ail. Ajouter les courgettes émincées. Persiller.",
        ["high-protein", "low-carb", "quick", "gluten-free"],
        ["crustaces"],
    ),
    # ── COLLATION ───────────────────────────────────────────────────────────
    (
        "Yaourt grec et amandes",
        200,
        16,
        "collation",
        "méditerranéenne",
        "végétarien",
        2,
        [
            {"name": "Yaourt grec", "quantity": 150, "unit": "g"},
            {"name": "Amandes", "quantity": 20, "unit": "g"},
            {"name": "Miel", "quantity": 10, "unit": "g"},
        ],
        "Verser le yaourt dans un bol. Ajouter les amandes et le miel.",
        ["high-protein", "vegetarian", "quick", "low-carb"],
        ["lactose", "noix"],
    ),
    (
        "Fromage blanc miel et noix",
        220,
        14,
        "collation",
        "française",
        "végétarien",
        2,
        [
            {"name": "Fromage blanc", "quantity": 150, "unit": "g"},
            {"name": "Noix", "quantity": 20, "unit": "g"},
            {"name": "Miel", "quantity": 10, "unit": "g"},
        ],
        "Mélanger fromage blanc et miel. Concasser les noix et ajouter dessus.",
        ["vegetarian", "quick", "high-protein"],
        ["lactose", "noix"],
    ),
    (
        "Pomme et beurre d'amande",
        240,
        6,
        "collation",
        "internationale",
        "vegan",
        2,
        [
            {"name": "Pomme", "quantity": 1, "unit": "pièce"},
            {"name": "Beurre d'amande", "quantity": 30, "unit": "g"},
        ],
        "Couper la pomme en tranches. Servir avec le beurre d'amande pour tremper.",
        ["vegan", "quick", "gluten-free", "natural"],
        ["noix"],
    ),
    (
        "Shake protéiné chocolat",
        260,
        24,
        "collation",
        "internationale",
        "végétarien",
        3,
        [
            {"name": "Lait demi-écrémé", "quantity": 250, "unit": "ml"},
            {"name": "Protéine en poudre chocolat", "quantity": 30, "unit": "g"},
            {"name": "Banane", "quantity": 0.5, "unit": "pièce"},
        ],
        "Mixer tous les ingrédients pendant 30 secondes. Servir immédiatement.",
        ["high-protein", "quick", "post-workout"],
        ["lactose"],
    ),
    (
        "Crackers houmous et crudités",
        220,
        8,
        "collation",
        "méditerranéenne",
        "vegan",
        5,
        [
            {"name": "Crackers de seigle", "quantity": 3, "unit": "pièces"},
            {"name": "Houmous", "quantity": 60, "unit": "g"},
            {"name": "Carotte", "quantity": 80, "unit": "g"},
            {"name": "Concombre", "quantity": 60, "unit": "g"},
        ],
        "Tartiner les crackers de houmous. Couper les légumes en bâtonnets. Déguster.",
        ["vegan", "quick", "fiber-rich"],
        ["gluten", "sesame"],
    ),
    (
        "Œufs durs au sel",
        160,
        14,
        "collation",
        "française",
        "végétarien",
        12,
        [
            {"name": "Œufs", "quantity": 2, "unit": "pièces"},
            {"name": "Sel", "quantity": 1, "unit": "pincée"},
        ],
        "Plonger les œufs dans l'eau bouillante 10 min. Refroidir et écaler.",
        ["high-protein", "vegetarian", "budget", "gluten-free", "quick"],
        ["oeuf"],
    ),
    (
        "Cottage cheese et fruits rouges",
        180,
        16,
        "collation",
        "internationale",
        "végétarien",
        2,
        [
            {"name": "Cottage cheese", "quantity": 150, "unit": "g"},
            {"name": "Fruits rouges mélangés", "quantity": 80, "unit": "g"},
        ],
        "Mélanger le cottage cheese et les fruits rouges dans un bol.",
        ["high-protein", "vegetarian", "low-cal", "quick"],
        ["lactose"],
    ),
    (
        "Mélange noix et raisins secs",
        280,
        6,
        "collation",
        "internationale",
        "vegan",
        1,
        [
            {"name": "Noix mélangées", "quantity": 30, "unit": "g"},
            {"name": "Raisins secs", "quantity": 20, "unit": "g"},
            {"name": "Cranberries séchées", "quantity": 15, "unit": "g"},
        ],
        "Mélanger noix et fruits secs dans un petit bol ou sachet.",
        ["vegan", "gluten-free", "energy", "portable"],
        ["noix"],
    ),
    (
        "Shake protéiné vanille et lait",
        240,
        24,
        "collation",
        "internationale",
        "végétarien",
        3,
        [
            {"name": "Lait demi-écrémé", "quantity": 250, "unit": "ml"},
            {"name": "Protéine en poudre vanille", "quantity": 30, "unit": "g"},
        ],
        "Shaker vigoureusement le lait et la protéine pendant 30 secondes.",
        ["high-protein", "quick", "post-workout"],
        ["lactose"],
    ),
    (
        "Banane et beurre de cacahuète",
        280,
        8,
        "collation",
        "internationale",
        "vegan",
        2,
        [
            {"name": "Banane", "quantity": 1, "unit": "pièce"},
            {"name": "Beurre de cacahuète", "quantity": 30, "unit": "g"},
        ],
        "Éplucher la banane. Tartiner ou tremper dans le beurre de cacahuète.",
        ["vegan", "gluten-free", "quick", "energy"],
        ["arachides"],
    ),
    # ── COLLATION (batch 2) ─────────────────────────────────────────────────
    (
        "Shaker protéiné eau",
        180,
        30,
        "collation",
        "internationale",
        "végétarien",
        1,
        [
            {"name": "Protéine en poudre vanille", "quantity": 35, "unit": "g"},
            {"name": "Eau", "quantity": 300, "unit": "ml"},
        ],
        "Shaker vigoureusement protéine et eau pendant 30 secondes.",
        ["high-protein", "low-fat", "quick", "portable"],
        [],
    ),
    (
        "Œufs durs et concombre",
        180,
        16,
        "collation",
        "française",
        "végétarien",
        12,
        [
            {"name": "Œufs", "quantity": 2, "unit": "pièces"},
            {"name": "Concombre", "quantity": 100, "unit": "g"},
            {"name": "Sel", "quantity": 1, "unit": "pincée"},
        ],
        "Cuire les œufs 10 min. Éplucher. Servir avec le concombre en bâtonnets.",
        ["high-protein", "low-carb", "budget", "gluten-free"],
        ["oeuf"],
    ),
    (
        "Skyr fruits et miel",
        200,
        22,
        "collation",
        "internationale",
        "végétarien",
        2,
        [
            {"name": "Skyr nature", "quantity": 150, "unit": "g"},
            {"name": "Fruits rouges", "quantity": 60, "unit": "g"},
            {"name": "Miel", "quantity": 10, "unit": "g"},
        ],
        "Verser le skyr dans un bol. Ajouter fruits et miel.",
        ["high-protein", "low-fat", "quick"],
        ["lactose"],
    ),
    (
        "Galettes de riz et beurre d'amande",
        200,
        6,
        "collation",
        "internationale",
        "vegan",
        2,
        [
            {"name": "Galettes de riz", "quantity": 3, "unit": "pièces"},
            {"name": "Beurre d'amande", "quantity": 20, "unit": "g"},
        ],
        "Tartiner les galettes de riz de beurre d'amande.",
        ["vegan", "gluten-free", "quick", "portable"],
        ["noix"],
    ),
    (
        "Fromage blanc protéiné",
        220,
        28,
        "collation",
        "française",
        "végétarien",
        2,
        [
            {"name": "Fromage blanc 0%", "quantity": 200, "unit": "g"},
            {"name": "Protéine en poudre vanille", "quantity": 15, "unit": "g"},
            {"name": "Miel", "quantity": 10, "unit": "g"},
        ],
        "Mélanger fromage blanc, whey et miel.",
        ["high-protein", "low-fat", "quick"],
        ["lactose"],
    ),
    (
        "Bâtonnets de carottes et houmous",
        180,
        6,
        "collation",
        "méditerranéenne",
        "vegan",
        3,
        [
            {"name": "Carotte", "quantity": 150, "unit": "g"},
            {"name": "Houmous", "quantity": 50, "unit": "g"},
        ],
        "Couper les carottes en bâtonnets. Servir avec le houmous.",
        ["vegan", "gluten-free", "low-cal", "quick"],
        ["sesame"],
    ),
    (
        "Tranches de dinde et pomme",
        180,
        20,
        "collation",
        "française",
        "omnivore",
        2,
        [
            {"name": "Blanc de dinde en tranches", "quantity": 80, "unit": "g"},
            {"name": "Pomme", "quantity": 1, "unit": "pièce"},
        ],
        "Rouler les tranches de dinde. Servir avec la pomme coupée en quartiers.",
        ["high-protein", "low-fat", "quick", "gluten-free"],
        [],
    ),
    (
        "Barres protéinées maison",
        260,
        20,
        "collation",
        "internationale",
        "végétarien",
        15,
        [
            {"name": "Flocons d'avoine", "quantity": 40, "unit": "g"},
            {"name": "Protéine en poudre chocolat", "quantity": 25, "unit": "g"},
            {"name": "Beurre de cacahuète", "quantity": 20, "unit": "g"},
            {"name": "Miel", "quantity": 15, "unit": "g"},
        ],
        "Mélanger tous les ingrédients. Former des barres. Réfrigérer 30 min.",
        ["high-protein", "meal-prep", "energy"],
        ["gluten", "arachides"],
    ),
    (
        "Edamame salé",
        160,
        14,
        "collation",
        "asiatique",
        "vegan",
        5,
        [
            {"name": "Edamame surgelé", "quantity": 120, "unit": "g"},
            {"name": "Sel de mer", "quantity": 2, "unit": "g"},
        ],
        "Cuire les edamame à l'eau bouillante 5 min. Saler et servir.",
        ["vegan", "high-protein", "gluten-free", "quick"],
        ["soja"],
    ),
    (
        "Yaourt protéiné granola",
        240,
        20,
        "collation",
        "internationale",
        "végétarien",
        2,
        [
            {"name": "Yaourt grec", "quantity": 150, "unit": "g"},
            {"name": "Granola", "quantity": 30, "unit": "g"},
        ],
        "Verser le yaourt dans un bol. Ajouter le granola.",
        ["high-protein", "quick"],
        ["lactose", "gluten"],
    ),
    (
        "Muffin protéiné banane",
        220,
        18,
        "collation",
        "internationale",
        "végétarien",
        25,
        [
            {"name": "Banane", "quantity": 1, "unit": "pièce"},
            {"name": "Protéine en poudre vanille", "quantity": 25, "unit": "g"},
            {"name": "Œuf", "quantity": 1, "unit": "pièce"},
            {"name": "Flocons d'avoine", "quantity": 30, "unit": "g"},
        ],
        "Mixer tous les ingrédients. Cuire en moule à muffin 15 min à 180°C.",
        ["high-protein", "meal-prep"],
        ["gluten", "oeuf"],
    ),
    (
        "Tartines de riz soufflé et confiture",
        160,
        2,
        "collation",
        "internationale",
        "vegan",
        2,
        [
            {"name": "Galettes de riz soufflé", "quantity": 3, "unit": "pièces"},
            {"name": "Confiture de fraises", "quantity": 20, "unit": "g"},
        ],
        "Tartiner les galettes de confiture.",
        ["vegan", "gluten-free", "quick", "low-fat"],
        [],
    ),
    (
        "Compote de pomme et fromage blanc",
        180,
        12,
        "collation",
        "française",
        "végétarien",
        2,
        [
            {"name": "Compote de pomme sans sucre", "quantity": 100, "unit": "g"},
            {"name": "Fromage blanc 0%", "quantity": 100, "unit": "g"},
        ],
        "Mélanger la compote et le fromage blanc.",
        ["vegetarian", "low-fat", "quick"],
        ["lactose"],
    ),
    (
        "Boules d'énergie dattes cacao",
        240,
        6,
        "collation",
        "internationale",
        "vegan",
        10,
        [
            {"name": "Dattes Medjool", "quantity": 4, "unit": "pièces"},
            {"name": "Poudre de cacao", "quantity": 10, "unit": "g"},
            {"name": "Flocons d'avoine", "quantity": 30, "unit": "g"},
            {"name": "Beurre de cacahuète", "quantity": 15, "unit": "g"},
        ],
        "Mixer les dattes. Mélanger avec cacao, avoine et beurre de cacahuète. Former des boules.",
        ["vegan", "energy", "meal-prep"],
        ["arachides", "gluten"],
    ),
    (
        "Fromage frais et radis",
        140,
        8,
        "collation",
        "française",
        "végétarien",
        5,
        [
            {"name": "Fromage frais", "quantity": 100, "unit": "g"},
            {"name": "Radis", "quantity": 80, "unit": "g"},
            {"name": "Pain complet", "quantity": 1, "unit": "tranche"},
        ],
        "Tartiner le pain de fromage frais. Trancher les radis dessus.",
        ["vegetarian", "light", "quick"],
        ["lactose", "gluten"],
    ),
    (
        "Pudding protéiné chocolat",
        200,
        24,
        "collation",
        "internationale",
        "végétarien",
        5,
        [
            {"name": "Lait demi-écrémé", "quantity": 200, "unit": "ml"},
            {"name": "Protéine en poudre chocolat", "quantity": 30, "unit": "g"},
            {"name": "Graines de chia", "quantity": 10, "unit": "g"},
        ],
        "Mélanger lait, whey et chia. Réfrigérer 2h minimum.",
        ["high-protein", "low-fat", "meal-prep"],
        ["lactose"],
    ),
    (
        "Thon et crackers",
        200,
        20,
        "collation",
        "internationale",
        "omnivore",
        3,
        [
            {"name": "Thon en conserve", "quantity": 80, "unit": "g"},
            {"name": "Crackers de seigle", "quantity": 3, "unit": "pièces"},
            {"name": "Citron", "quantity": 0.25, "unit": "pièce"},
        ],
        "Égoutter le thon. Répartir sur les crackers. Arroser de citron.",
        ["high-protein", "quick", "portable"],
        ["gluten", "poisson"],
    ),
    (
        "Smoothie protéiné fraise",
        220,
        24,
        "collation",
        "internationale",
        "végétarien",
        3,
        [
            {"name": "Fraises surgelées", "quantity": 100, "unit": "g"},
            {"name": "Protéine en poudre vanille", "quantity": 25, "unit": "g"},
            {"name": "Lait demi-écrémé", "quantity": 200, "unit": "ml"},
        ],
        "Mixer fraises, whey et lait jusqu'à consistance lisse.",
        ["high-protein", "quick", "post-workout"],
        ["lactose"],
    ),
    (
        "Wrap dinde et concombre",
        200,
        18,
        "collation",
        "internationale",
        "omnivore",
        3,
        [
            {"name": "Tortilla de blé", "quantity": 1, "unit": "pièce"},
            {"name": "Blanc de dinde en tranches", "quantity": 60, "unit": "g"},
            {"name": "Concombre", "quantity": 60, "unit": "g"},
        ],
        "Garnir la tortilla de dinde et concombre. Rouler.",
        ["high-protein", "quick", "portable"],
        ["gluten"],
    ),
    (
        "Amandes et chocolat noir",
        240,
        6,
        "collation",
        "internationale",
        "vegan",
        1,
        [
            {"name": "Amandes", "quantity": 25, "unit": "g"},
            {"name": "Chocolat noir 85%", "quantity": 20, "unit": "g"},
        ],
        "Associer amandes et carrés de chocolat noir.",
        ["vegan", "gluten-free", "energy", "portable"],
        ["noix"],
    ),
    # ── NEW BATCH — filling gaps ─────────────────────────────────────────────
    # Petit-déjeuner: skyr bowl, more egg variety, overnight oats
    (
        "Skyr bowl myrtilles et graines",
        350,
        30,
        "petit-dejeuner",
        "nordique",
        "végétarien",
        5,
        [
            {"name": "Skyr nature", "quantity": 200, "unit": "g"},
            {"name": "Myrtilles", "quantity": 80, "unit": "g"},
            {"name": "Graines de chia", "quantity": 10, "unit": "g"},
            {"name": "Graines de tournesol", "quantity": 15, "unit": "g"},
            {"name": "Miel", "quantity": 10, "unit": "g"},
        ],
        "Verser le skyr dans un bol. Ajouter les myrtilles, graines de chia et tournesol. Filet de miel.",
        ["high-protein", "vegetarian", "quick", "low-fat"],
        ["lactose"],
    ),
    (
        "Overnight oats poire cannelle",
        380,
        14,
        "petit-dejeuner",
        "internationale",
        "végétarien",
        5,
        [
            {"name": "Flocons d'avoine", "quantity": 70, "unit": "g"},
            {"name": "Lait d'amande", "quantity": 200, "unit": "ml"},
            {"name": "Poire", "quantity": 1, "unit": "pièce"},
            {"name": "Cannelle", "quantity": 2, "unit": "g"},
            {"name": "Graines de lin", "quantity": 10, "unit": "g"},
        ],
        "Mélanger avoine, lait et lin. Réfrigérer une nuit. Ajouter poire coupée et cannelle.",
        ["high-fiber", "vegetarian", "meal-prep"],
        ["gluten", "noix"],
    ),
    (
        "Œufs brouillés épinards et tomates",
        320,
        24,
        "petit-dejeuner",
        "méditerranéenne",
        "végétarien",
        10,
        [
            {"name": "Œufs", "quantity": 3, "unit": "pièces"},
            {"name": "Épinards frais", "quantity": 60, "unit": "g"},
            {"name": "Tomates cerises", "quantity": 80, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 5, "unit": "ml"},
        ],
        "Faire revenir les épinards et tomates. Ajouter les œufs battus. Brouiller à feu doux.",
        ["high-protein", "low-carb", "vegetarian", "quick"],
        ["oeuf"],
    ),
    (
        "Pancakes protéinés à la banane",
        400,
        28,
        "petit-dejeuner",
        "internationale",
        "végétarien",
        15,
        [
            {"name": "Banane mûre", "quantity": 1, "unit": "pièce"},
            {"name": "Œufs", "quantity": 2, "unit": "pièces"},
            {"name": "Flocons d'avoine", "quantity": 50, "unit": "g"},
            {"name": "Fromage blanc", "quantity": 50, "unit": "g"},
            {"name": "Cannelle", "quantity": 2, "unit": "g"},
        ],
        "Mixer banane, œufs, avoine et fromage blanc. Cuire en petits pancakes 2 min/face.",
        ["high-protein", "vegetarian"],
        ["gluten", "oeuf", "lactose"],
    ),
    (
        "Tartine complète ricotta et figues",
        360,
        16,
        "petit-dejeuner",
        "méditerranéenne",
        "végétarien",
        5,
        [
            {"name": "Pain complet", "quantity": 2, "unit": "tranches"},
            {"name": "Ricotta", "quantity": 60, "unit": "g"},
            {"name": "Figues fraîches", "quantity": 2, "unit": "pièces"},
            {"name": "Miel", "quantity": 10, "unit": "g"},
            {"name": "Noix", "quantity": 10, "unit": "g"},
        ],
        "Toaster le pain. Tartiner de ricotta. Ajouter figues coupées, noix concassées et miel.",
        ["vegetarian", "quick", "mediterranean"],
        ["gluten", "lactose", "noix"],
    ),
    # Déjeuner: more Mediterranean, legume-based, chicken variety
    (
        "Salade de lentilles vertes et feta",
        480,
        26,
        "dejeuner",
        "méditerranéenne",
        "végétarien",
        20,
        [
            {"name": "Lentilles vertes", "quantity": 150, "unit": "g"},
            {"name": "Feta", "quantity": 40, "unit": "g"},
            {"name": "Concombre", "quantity": 80, "unit": "g"},
            {"name": "Tomates cerises", "quantity": 80, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 10, "unit": "ml"},
            {"name": "Jus de citron", "quantity": 10, "unit": "ml"},
        ],
        "Cuire les lentilles. Refroidir. Mélanger avec concombre, tomates, feta. Assaisonner.",
        ["high-fiber", "vegetarian", "high-protein", "mediterranean"],
        ["lactose"],
    ),
    (
        "Poulet citron et couscous aux légumes",
        520,
        38,
        "dejeuner",
        "méditerranéenne",
        "omnivore",
        25,
        [
            {"name": "Blanc de poulet", "quantity": 180, "unit": "g"},
            {"name": "Couscous complet", "quantity": 80, "unit": "g"},
            {"name": "Courgette", "quantity": 80, "unit": "g"},
            {"name": "Poivron rouge", "quantity": 60, "unit": "g"},
            {"name": "Citron", "quantity": 0.5, "unit": "pièce"},
            {"name": "Huile d'olive", "quantity": 10, "unit": "ml"},
        ],
        "Griller le poulet mariné au citron. Préparer le couscous. Sauter les légumes. Assembler.",
        ["high-protein", "balanced", "mediterranean"],
        ["gluten"],
    ),
    (
        "Soupe de haricots blancs et kale",
        420,
        22,
        "dejeuner",
        "internationale",
        "vegan",
        25,
        [
            {"name": "Haricots blancs", "quantity": 200, "unit": "g"},
            {"name": "Kale", "quantity": 100, "unit": "g"},
            {"name": "Oignon", "quantity": 1, "unit": "pièce"},
            {"name": "Ail", "quantity": 2, "unit": "pièces"},
            {"name": "Tomates concassées", "quantity": 150, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 10, "unit": "ml"},
        ],
        "Faire revenir oignon et ail. Ajouter tomates, haricots et kale. Mijoter 15 min.",
        ["vegan", "high-fiber", "budget", "comfort"],
        [],
    ),
    (
        "Bol méditerranéen pois chiches rôtis",
        500,
        22,
        "dejeuner",
        "méditerranéenne",
        "vegan",
        25,
        [
            {"name": "Pois chiches", "quantity": 200, "unit": "g"},
            {"name": "Patate douce", "quantity": 150, "unit": "g"},
            {"name": "Épinards frais", "quantity": 60, "unit": "g"},
            {"name": "Tahini", "quantity": 15, "unit": "g"},
            {"name": "Citron", "quantity": 0.5, "unit": "pièce"},
            {"name": "Paprika fumé", "quantity": 3, "unit": "g"},
        ],
        "Rôtir pois chiches et patate douce au paprika. Assembler sur épinards. Sauce tahini-citron.",
        ["vegan", "high-fiber", "mediterranean", "meal-prep"],
        ["sesame"],
    ),
    (
        "Wrap poulet avocat et crudités",
        520,
        36,
        "dejeuner",
        "internationale",
        "omnivore",
        10,
        [
            {"name": "Tortilla de blé complet", "quantity": 1, "unit": "pièce"},
            {"name": "Blanc de poulet cuit", "quantity": 150, "unit": "g"},
            {"name": "Avocat", "quantity": 60, "unit": "g"},
            {"name": "Tomate", "quantity": 60, "unit": "g"},
            {"name": "Laitue", "quantity": 30, "unit": "g"},
        ],
        "Garnir la tortilla de poulet, avocat écrasé, tomate et laitue. Rouler serré.",
        ["high-protein", "quick", "portable"],
        ["gluten"],
    ),
    # Dîner: more fish, vegetable-heavy mains
    (
        "Filet de truite aux amandes et haricots verts",
        380,
        36,
        "diner",
        "française",
        "omnivore",
        20,
        [
            {"name": "Filet de truite", "quantity": 180, "unit": "g"},
            {"name": "Amandes effilées", "quantity": 15, "unit": "g"},
            {"name": "Haricots verts", "quantity": 150, "unit": "g"},
            {"name": "Beurre", "quantity": 10, "unit": "g"},
            {"name": "Citron", "quantity": 0.5, "unit": "pièce"},
        ],
        "Poêler la truite côté peau. Dorer les amandes au beurre. Cuire les haricots vapeur.",
        ["high-protein", "omega3", "low-carb"],
        ["poisson", "noix", "lactose"],
    ),
    (
        "Dos de lieu noir et purée de brocolis",
        340,
        38,
        "diner",
        "française",
        "omnivore",
        20,
        [
            {"name": "Filet de lieu noir", "quantity": 200, "unit": "g"},
            {"name": "Brocolis", "quantity": 200, "unit": "g"},
            {"name": "Crème légère", "quantity": 30, "unit": "ml"},
            {"name": "Ail", "quantity": 1, "unit": "pièce"},
            {"name": "Huile d'olive", "quantity": 5, "unit": "ml"},
        ],
        "Cuire le lieu noir à la poêle. Cuire brocolis vapeur, mixer avec crème et ail.",
        ["high-protein", "low-carb", "light"],
        ["poisson", "lactose"],
    ),
    (
        "Aubergines farcies au quinoa et légumes",
        360,
        16,
        "diner",
        "méditerranéenne",
        "vegan",
        30,
        [
            {"name": "Aubergine", "quantity": 1, "unit": "pièce"},
            {"name": "Quinoa", "quantity": 60, "unit": "g"},
            {"name": "Poivron rouge", "quantity": 60, "unit": "g"},
            {"name": "Oignon", "quantity": 0.5, "unit": "pièce"},
            {"name": "Tomates concassées", "quantity": 100, "unit": "g"},
            {"name": "Cumin", "quantity": 2, "unit": "g"},
        ],
        "Évider l'aubergine. Cuire le quinoa. Mélanger avec légumes sautés. Farcir et cuire au four.",
        ["vegan", "high-fiber", "mediterranean"],
        [],
    ),
    (
        "Poêlée de dinde aux légumes d'automne",
        400,
        38,
        "diner",
        "française",
        "omnivore",
        20,
        [
            {"name": "Escalope de dinde", "quantity": 180, "unit": "g"},
            {"name": "Butternut", "quantity": 120, "unit": "g"},
            {"name": "Champignons", "quantity": 100, "unit": "g"},
            {"name": "Oignon rouge", "quantity": 0.5, "unit": "pièce"},
            {"name": "Thym", "quantity": 2, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 10, "unit": "ml"},
        ],
        "Couper dinde en dés. Saisir avec butternut et champignons. Assaisonner au thym.",
        ["high-protein", "balanced", "seasonal"],
        [],
    ),
    (
        "Sardines grillées et salade de tomates",
        380,
        30,
        "diner",
        "méditerranéenne",
        "omnivore",
        15,
        [
            {"name": "Sardines fraîches", "quantity": 200, "unit": "g"},
            {"name": "Tomates", "quantity": 150, "unit": "g"},
            {"name": "Oignon rouge", "quantity": 30, "unit": "g"},
            {"name": "Huile d'olive", "quantity": 10, "unit": "ml"},
            {"name": "Basilic frais", "quantity": 5, "unit": "g"},
            {"name": "Pain complet", "quantity": 1, "unit": "tranche"},
        ],
        "Griller les sardines 3 min/face. Préparer la salade de tomates, oignon rouge et basilic.",
        ["high-protein", "omega3", "mediterranean", "quick", "budget"],
        ["poisson", "gluten"],
    ),
    # Collation: whole-food options, less shake-dependent
    (
        "Carottes et houmous maison",
        180,
        8,
        "collation",
        "méditerranéenne",
        "vegan",
        5,
        [
            {"name": "Carottes", "quantity": 120, "unit": "g"},
            {"name": "Houmous", "quantity": 60, "unit": "g"},
        ],
        "Couper les carottes en bâtonnets. Servir avec le houmous.",
        ["vegan", "gluten-free", "quick", "low-calorie"],
        ["sesame"],
    ),
    (
        "Skyr vanille et fruits secs",
        200,
        22,
        "collation",
        "nordique",
        "végétarien",
        2,
        [
            {"name": "Skyr vanille", "quantity": 150, "unit": "g"},
            {"name": "Abricots secs", "quantity": 20, "unit": "g"},
            {"name": "Amandes", "quantity": 10, "unit": "g"},
        ],
        "Verser le skyr dans un bol. Ajouter abricots secs et amandes.",
        ["high-protein", "vegetarian", "quick", "portable"],
        ["lactose", "noix"],
    ),
    (
        "Galette de riz et beurre de cacahuète",
        200,
        8,
        "collation",
        "internationale",
        "vegan",
        2,
        [
            {"name": "Galettes de riz", "quantity": 2, "unit": "pièces"},
            {"name": "Beurre de cacahuète", "quantity": 20, "unit": "g"},
            {"name": "Banane", "quantity": 0.5, "unit": "pièce"},
        ],
        "Tartiner les galettes de beurre de cacahuète. Ajouter rondelles de banane.",
        ["vegan", "quick", "portable", "energy"],
        ["arachides"],
    ),
    (
        "Œuf dur et bâtonnets de concombre",
        140,
        12,
        "collation",
        "internationale",
        "végétarien",
        5,
        [
            {"name": "Œufs", "quantity": 2, "unit": "pièces"},
            {"name": "Concombre", "quantity": 100, "unit": "g"},
            {"name": "Sel et poivre", "quantity": 1, "unit": "pincée"},
        ],
        "Cuire les œufs durs 10 min. Couper le concombre en bâtonnets.",
        ["high-protein", "low-carb", "gluten-free", "quick"],
        ["oeuf"],
    ),
    (
        "Compote de pommes maison et noix",
        160,
        4,
        "collation",
        "française",
        "vegan",
        15,
        [
            {"name": "Pommes", "quantity": 2, "unit": "pièces"},
            {"name": "Cannelle", "quantity": 2, "unit": "g"},
            {"name": "Noix", "quantity": 15, "unit": "g"},
        ],
        "Couper les pommes en dés. Cuire à feu doux 10 min avec la cannelle. Ajouter les noix.",
        ["vegan", "gluten-free", "whole-food", "low-calorie"],
        ["noix"],
    ),
]


def build_recipe_row(recipe_tuple: tuple) -> dict:
    (
        name,
        calories,
        protein_g,
        meal_type,
        cuisine,
        diet,
        prep_min,
        ingredients,
        instructions,
        tags,
        allergen_tags,
    ) = recipe_tuple

    macros = calculate_macros(calories, protein_g, goal_type="maintenance")

    return {
        "name": name,
        "name_normalized": normalize(name),
        "description": f"{name} — recette équilibrée {cuisine}.",
        "meal_type": meal_type,
        "cuisine_type": cuisine,
        "diet_type": diet,
        "prep_time_minutes": prep_min,
        "ingredients": ingredients,
        "instructions": instructions,
        "tags": tags,
        "allergen_tags": allergen_tags,
        "calories_per_serving": float(calories),
        "protein_g_per_serving": float(protein_g),
        "carbs_g_per_serving": float(macros["carbs_g"]),
        "fat_g_per_serving": float(macros["fat_g"]),
        "source": "manual",
        "off_validated": False,
    }


async def seed(supabase) -> None:
    counts = {"petit-dejeuner": 0, "dejeuner": 0, "diner": 0, "collation": 0}
    failed = 0
    validated = 0

    for recipe_tuple in RECIPES:
        row = build_recipe_row(recipe_tuple)
        try:
            # OFF-validate to get real macros before storing
            row = await off_validate_recipe(row, supabase)
            if row.get("off_validated"):
                validated += 1

            supabase.table("recipes").upsert(
                row, on_conflict="name_normalized"
            ).execute()
            counts[row["meal_type"]] += 1
            logger.info(
                f"  ✓ {row['name']} ({row['calories_per_serving']:.0f} kcal, "
                f"OFF={'✓' if row.get('off_validated') else '✗'})"
            )
        except Exception as e:
            logger.error(f"  ✗ {row['name']}: {e}")
            failed += 1

    total = sum(counts.values())
    logger.info(
        f"\nDone: {total} upserted, {failed} failed, {validated} OFF-validated."
    )
    logger.info(f"Coverage: {counts}")


if __name__ == "__main__":
    supabase = get_supabase_client()
    asyncio.run(seed(supabase))
